import { Box, Flex, List, ListItem, Text } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { Header } from "../Header";
import Navbar from '../Navbar'

interface Page {
  name: string;
  url: string;
}

const PAGES: Page[] = [
  { name: "Home", url: "/" },
  { name: "Users", url: "/users" },
  { name: "Auth", url: "/auth" },
  { name: "User List using toolkit", url: "/user-list" },
  { name: "User List using rtk", url: "/user-list-rtk" },
];

export const Layout: React.FC<any> = ({ children }) => {
  return (
    <>
      <Head>
        <title>FE BOOTCAMP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" w={"full"} h={"100vh"}>
        <Navbar />
        {/* <div>
          test
        </div> */}
        <Box h="full">
          { children }
        </Box>
        {/* <Flex width="100%" w="20%">
          <Flex bg="black">
            Hello World
          </Flex>
        </Flex> */}
        {/* <Box w={"80vw"} ml={"20vw"} bg={"white"}>
          <Header />
          <Box bg={"white"} p={4}>
          {children}
          </Box>
        </Box> */}
      </Flex>
    </>
  );
};
